public class Curriculo {
	public static void main (String[] args){
        System.out.print("\n");
		System.out.print("Curriculo profissional\n");
        System.out.print("\n");
        System.out.print("Nome: Vinicius Araujo de Figueiredo\n");
        System.out.print("E-mail: viniciusaraujo.145@outlook.com\n");
        System.out.print("Telefone: (83) 9 9650-7401\n");
        System.out.print("Idade: 21 anos\n");
        System.out.print("Data de nascimento: 11/11/2001\n");
        System.out.print("Estado: PB\n");
        System.out.print("Cidade: Patos\n");
        System.out.print("_______________________________________________________________________________________________\n");
        System.out.print("\n");
        System.out.print("OBJETIVO\n");
        System.out.print("\n");
        System.out.print("Busco uma experiencia na minha area de atuacao (TI), onde pretendo compartilhar e absorver conhecimento com o exercicio oferecido, e contribuir assim, no andamento do mercado de trabalho envolvido.\n");
        System.out.print("_______________________________________________________________________________________________\n");
        System.out.print("\n");
        System.out.print("EXPERIENCIA\n");
        System.out.print("\n");
        System.out.print("Nova Vale Chevrolet: De 15/07/2019 a 10/01/2020:\n");
        System.out.print("Funcao: Auxiliar de escritorio em geral (Jovem Aprendiz pelo CIEE)\n");
        System.out.print("\n");
        System.out.print("Nova Vale Chevrolet: De 21/01/2020 a 27/01/2021:\n");
        System.out.print("Funcao: Estoquista (Emprego formal)\n");
        System.out.print("\n");
        System.out.print("Operacao Resgate: De 12/08/2021 a 12/11/2021:\n");
        System.out.print("Professor de informatica (Contrato de 3 meses)\n");
        System.out.print("\n");
        System.out.print("Nova Vale Chevrolet: De 10/03/2022 a 20/05/2022:\n");
        System.out.print("Operador de Caixa (Emprego formal)\n");
        System.out.print("\n");
        System.out.print("Dao Silveira Chevrolet: De 15/06/2022 a 30/08/2022:\n");
        System.out.print("Operador de caixa (Emprego formal)\n");
        System.out.print("\n");
        System.out.print("Dao Silveira Chevrolet: De 31/08/2022 a 01/11/2022:\n");
        System.out.print("Professor de informatica (Contrato de 3 meses)\n");
        System.out.print("\n");
        System.out.print("Design Grafico: Desde 02/2021:\n");
        System.out.print("Autonomo\n");
        System.out.print("_______________________________________________________________________________________________\n");
        System.out.print("\n");
        System.out.print("FORMACAO\n");
        System.out.print("\n");
        System.out.print("Cursando Ensino Superior\n");
        System.out.print("Universidade Estadual da Paraiba (UEPB)\n");
        System.out.print("Turno: Noturno\n");
        System.out.print("Curso: Ciencias da Computacao\n");
        System.out.print("Periodo: P5\n");
        System.out.print("_______________________________________________________________________________________________\n");
        System.out.print("\n");
        System.out.print("CONHECIMENTOS\n");
        System.out.print("\n");
        System.out.print("EXCEL: Desde cedo adquiri gosto por gerenciar minha rotina e tarefas atraves do Excel, o que facilitou pra que utilizasse a ferramenta para agilizar meu trabalho onde quer que obtivesse uma oportunidade. Gosto de utilizar o Excel, pois ele viabiliza que eu unifique todas as ferramentas necessarias em um so documento e realize tarefas de forma mais agil atraves de formulas, hiperlinks, validacao de dados entre outros aspectos da ferramenta.\n");
        System.out.print("WORD: Ao mesmo tempo que valorizo o trabalho do Excel, o Word tambem me auxilia na construcao de alguns documentos de texto. Nao conheco tanto da plataforma quanto conheco do Excel, mas sei utilizar suficientemente bem para resolver os problemas recorrentes do dia-a-dia.\n");
        System.out.print("PYTHON: A linguagem de programacao Python tem feito parte do meu desenvolvimento profissional desde o primeiro periodo do meu ingresso na faculdade. Atraves dela tive a oportunidade de desenvolver alguns projetos simples, e tenho desde entao desenvolvido meu entendimento em programacao principalmente nesta linguagem. Acredito que com uma boa oportunidade, consigo unir o conhecimento do Excel e do Python para desenvolver os mais diversos tipos de projetos.\n");
        System.out.print("JAVA: O conhecimento que obtive ao longo do tempo na linguagem foi bem pouco, mas obtive conhecimento o suficiente para conseguir entender como posso manipular um projeto orientado a objeto.\n");
	}
}